# -*- coding: utf-8 -*-
"""AI/ML_day2(pandas).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2K8n3S8XZTZ6AE-WwtwT4fj3NsPajaV
"""

#pandas
import pandas as pd
import numpy as np
print(pd.__version__)

ss=pd.Series([1,2,3,4,5,6])
print(ss)#int display the values along with its index

ss.dtype

ss.index #index detailing

ss=pd.Series([1,2,3,4,5,6], index=[3,4,5,6,7,8]) #changing the index manually
print(ss)

#Dataframe from nested list
lst=[[101,'fervin','fidha',22,'kozhikode'],
     [102,'nidha','ibrahim',23,'kozhikode'],
     [103,'rahma','jumana',22,'kozhikode'],
     [104,'shaziya','jabeen',22,'kannue'],]
print(lst)

df=pd.DataFrame(lst, columns=['id','fname','lname','age','place']) #coverting the list into dataframe, it also rename the cols
print(df)

df

df.head(2)# returns 2 rows

df.head() #first 5 rows get diplayed

df.tail(2) #last 2 rows

df.dtypes #cheching the datatype

df.describe() #returns the numerical descrptions of the numerical cols only

#Object Description

df.describe(include='O')

#Dataframe from Dictionary

dict_data={
    'id':[101,102,103,104],
    'fname':['fervin','nidha','rahma','shaziya'],
    'lname':['fidha','ibrahim','jumana','jabeen'],
    'age':[22,23,22,22],
    'place':['kozhikode','kozhikode','kozhikode','kannur']
}
print(dict_data)

dict_data

df_dict=pd.DataFrame(dict_data)
df_dict

df_dict.head(2)

df.tail(2)

df_dict['fname']

df_dict['place']

#multiple cols
df_dict[['fname','age']]

#loc (specif location data accessing)

df_dict.loc[0:1,['fname','age']] # locp[rowa:cols],[col name]

#iloc (integer based loction access)

df.iloc[0:2,[1,2]] # [rows:cols,[cols index]]

df.loc[df['age']>22,['fname','age']] #condition vech ulla printing

df['age']>22

df['place']=='kannue'

df[df['age']>22]

