# -*- coding: utf-8 -*-
"""AI/ML_Day5_Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UxTtmsu5nbaE3MU_7B6WvTepHtMB0V9P
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# prompt: read jpg image

# Read the image
img = cv2.imread("/content/nezuko.jpeg")
# Convert the image to RGB for displaying with matplotlib
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# Display the image
plt.imshow(img)

#size of image
img.shape

#image resize
image_resize = cv2.resize(img,(512,512))
plt.imshow(image_resize)

#Rotate Image
rt_img = cv2.rotate(image_resize,cv2.ROTATE_90_CLOCKWISE)
plt.imshow(rt_img)

#Smoothen Image
blur_img = cv2.blur(image_resize,(10,10))
plt.imshow(blur_img)

# convert an image from one color space to another
gray_img = cv2.cvtColor(image_resize,cv2.COLOR_RGB2GRAY)
plt.imshow(gray_img,cmap='gray')

