# -*- coding: utf-8 -*-
"""AI/ML day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prGd0kc9Z0e8x6TobLV9NGi9Gp5Eo4ua
"""

print("hello world")

num=10
print("number:",num)

_num2=45
print(_num2)

#hai=90

help('keywords')

print(type(num))

"""
first
second
third"""

#Aritmetic operations
a=10
b=9
print(a+b) #Addition
print(a-b) #subraction
print(a*b) #Multipication
print(a/b) #divison
print(a%b) #modulas
print(a//b) #floordivision
print(a**b) #power

x=14
y=3
print(x/y)
print(x//y)

"""Relational ***Operators***"""

print(a<b)

print(a>b)

print(a!=b)

a=10
print(a)
a+=5
print(a)

a-=10
print(a)

#logical Operators

print(a>4 and b<10)

print(a<4 or b<10)

print(not(a==b))

a=input("enter a number:")
print(a)

print(type(a))

a=int(input("enter a number:"))
print(a)

print(type(a))

b=float(input("enter a number:"))

print(b)

print(type(b))

name=input("Enter your name:")
age=int(input("Enter your age:"))
college=input("enter your collage name:")

print("Name:",name)
print("Age:",age)
print("college:",college)

print(f'{name} {age} years old studied in {college}') #formatted input

#String
str1="python programming"
print(str1)

#len
print(len(str1))

#forward indexing
#0 1 2.....

#backward indexing
#-1 -2......

print(str1[0])
print(str1[-1])
print(str1[3])

#string Operations
str1="hello WORLD"

#title
print(str1.title())

#lower
print(str1.lower())

#upper
print(str1.upper())

#count
str2="hai hellow world hello hello"
print(str2.count('hello'))
print(str2.count("hel",8,25)) #8,25 means starting and ending index and the word between in that index

#find
print(str2.find("hello")) #return the starting index of the word
print(str2.find("wor",10,20))# to find the between the index

#endswith and startwith
str1="Hello World!"
print(str1.endswith('!'))
print(str1.endswith('Hello'))

print(str1.startswith("Hello"))
print(str1.startswith("!"))

#islower()
str1="hello"
str2="Hello"
print(str1.islower())
print(str2.islower())

#isupper()
str1="HELLO"
str2="Hello"
print(str1.isupper())
print(str2.isupper())

#lstrip (to remove thwe space towards left)
str1=' Hello World! '
print(str1)
print(str1.lstrip())

#rstrip
print(str1.rstrip())

#strip (to remove left and right space)
print(str1.strip())

#replace
str1="Hello World"
print(str1.replace('o','*'))
print(str1.replace('World','country'))

#split
str1='there is a dog named fervin. we call her patti fervi'
print(str1.split())

str2='there,is,a,dog'
print(str2.split(','))

#desicion making statements
#1.if else
age=int(input("Enter yor age:"))
if age>=18:
  print("you can vote")
else:
  print("You can't vote")

#2 elif
num=int(input("Enter a Number:"))
if num>0:
  print(num," is Positive")
elif num==0:
  print(num," is Zero")
else:
  print(num," is Negative")

#largest among 2 number
num1=int(input("enter a number"))
num2=int(input("enter a number"))
if num1>num2:
  print(num1," is larger")
elif num1==num2:
  print(num1 ,"Equal")
else:
  print(num2," is larger")

#while loop
i=0
while i<=10:
  print(i)
  i+=1

for i in range(0,11,2):
  print(i)

#collection datatype:
#List[]
#Tuple
#dictionary
#set

#list

lst=[10,20,20,'python',True] #empty list , support hetronegous of data, defined using[],allows duplicates, mutable
list1=list() #using list function
print(lst)

print(lst[2])

lst[2]=50
print(lst)

for i in lst:
  print(i)

lst=[10,20,30,40]
#sum
print("sum",sum(lst))
print("max",max(lst))
print("len",len(lst))
print("min",min(lst))

#append

lst.append(50)
lst.append('hai')
print(lst)

#extend ( to add multiple elements)
lst.extend((1,5))
print(lst)

#insert
lst.insert(2,100) #insert the elemnet to the specified index
print(lst)

#sort
lst=[30,20,25,10]
lst.sort() #ascending
print(lst)

lst.sort(reverse=True) #desending
print(lst)

#remove
lst.remove(20) #specify the element
print(lst)

#pop
lst.pop() #last element will be removed
print(lst)

lst=[34,78,12,45,6]
lst.pop(2) #remove the element from that index
print(lst)

#list slicing
#[start:end-1:step]
lst=[1,5,25,67,34,89,1,0,45,24,27,55,14]
print(lst[2:9:2])

print(lst[5:])

print(lst[:7])

print(lst[:])

print(lst[2:10:2])

print(lst[-1])

