# -*- coding: utf-8 -*-
"""AL/ML_day2(numpy).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CoaZfBcXrGOdc3YfPdktXcMoXW9_pr1-
"""

#NumPy

import numpy as np

print(np.__version__) #for version

#1D Array
a = np.array([4,5,6,7,3,4,5,6])
print(a)

#dimension
print(a.ndim)

#shape
print(a.shape)

#size
print(a.size)

#datatype

print(a.dtype)

#2D Array
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

#dimension
print(b.ndim)

#shape
print(b.shape) #display the no of rows and cols

#size
print(b.size)

#datatype
print(b.dtype)

#Array creation function
#zero function to creat an array wth zeros
zeros_id=np.zeros(5, dtype=int) # always takes in float method so we can make it int

print(zeros_id.ndim)
print(zeros_id.dtype)

zeros_2d=np.zeros((2,5), dtype=int) # 2 rows and 5 cols
print(zeros_2d)

print(zeros_2d.ndim)
print(zeros_2d.dtype)

#ones

ones_arr=np.ones((3,3), dtype=int)
print(ones_arr)

#fulls (which value should be filled in array with any values)

full_arr=np.full((2,4),7)
print(full_arr)

full_arr2=np.full((3,4),5)
print(full_arr2)

#range

arr1=np.arange(1,10) # which means 1 to 9 elements get add
print(arr1)

arr2=np.arange(0,20,2) #same liek range()
print(arr2)

#linspace

lin1=np.linspace(0,10,5) #return equal interavl of 5 points(dividing into equal parts)
print(lin1)

#random

random_1d=np.random.rand(5) #genarating 1d with random values b/w 1 to 10 decimal values
print(random_1d)

rand_int=np.random.randint(1,100,10) #random values in integer 1 to 100 we need 10 values
print(rand_int)

#Reshape
arr= np.arange(12)
print(arr)

reshaped_2d=arr.reshape(3,4) #converting the 1d to 2d with same elements
print(reshaped_2d)

#flatten :converting the 2d to 1d

flat= reshaped_2d.flatten()
print(flat)

#indexing

print(flat[1:4]) #slicing
print(flat[::2])

arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

print(arr_2d[1])# 1nd index row will be displayed
print(arr_2d[1,2]) #single element access

print(arr_2d[:,2]) #every rows and 2nd index cols

print(arr_2d[1,:]) #print(arr_2d[1])# 1nd index row will be displayed [same as this]

# Square
arr=np.array([4,5,6,7,3,4,5,6])
print(np.square(arr))#sqaure of the elements

#square root
print(np.sqrt(arr))

#sum
print(np.sum(arr))

#mean
print(np.mean(arr))

#max and min
print(np.max(arr))
print(np.min(arr))

arr=np.array([10,4,9,6,5])
print(arr)

#sort
print(np.sort(arr))

print(np.sort(arr)[::-1]) #to sort descending order

