# -*- coding: utf-8 -*-
"""Copy of project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YMMTHNjCFIWLL18Ll9iOyxH3FIxbfM3Y
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#pd.read_csv(...) → uses pandas to read a CSV file.
#The file is stored at the given URL (GitHub link).
#The function loads the CSV file into a pandas DataFrame.
#df → is the variable name that stores this DataFrame.
df=pd.read_csv('https://raw.githubusercontent.com/tech4alltraining/aiml/refs/heads/main/datasets/classification/project/credit_score.csv')
df

#dependent/target variable: Credit_Score
#independent : Month,Age,Occupation  Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  Num_Credit_Card  Interest_Rate  Num_of_Loan  Type_of_Loan  Delay_from_due_date  Num_of_Delayed_Payment  Changed_Credit_Limit  Num_Credit_Inquiries  Credit_Mix  Outstanding_Debt  Credit_Utilization_Ratio  Credit_History_Age  Payment_of_Min_Amount  Total_EMI_per_month  Amount_invested_monthly  Payment_Behaviour  Monthly_Balance
# no need :ID,Customer_ID,Name,SSN
#doubt : age , anual etc is in object (should convert or not)

#Detemines the no of rows and cols of the dataset
df.info()

#detemines the datatypes of each cols
df.dtypes

df.shape

#statistics description
df.describe()

df.dtypes

# Columns that should be integers
int_columns = [
    'Age',
    'Num_Bank_Accounts',
    'Num_Credit_Card',
    'Interest_Rate',
    'Num_of_Loan',
    'Delay_from_due_date',
    'Num_of_Delayed_Payment',
    'Num_Credit_Inquiries'
]

# Other numeric columns that should be floats
float_columns = [
    'Annual_Income',
    'Changed_Credit_Limit',
    'Outstanding_Debt',
    'Amount_invested_monthly',
    'Monthly_Balance'
]

# Function to clean and convert
def clean_numeric(series):
    return pd.to_numeric(
        series.astype(str)               # ensure string
              .str.replace(r'[^\d\.-]', '', regex=True),  # remove non-numeric chars
        errors='coerce'
    )

# Convert integer columns
for col in int_columns:
    df[col] = clean_numeric(df[col]).astype('Int64')  # nullable int

# Convert float columns
for col in float_columns:
    df[col] = clean_numeric(df[col]).astype('float64')

# Check result
print(df[int_columns + float_columns].dtypes)
#This code cleans and converts selected object columns into proper numeric types (integers or floats) and then prints their new data types to verify.

df.dtypes

df.isna().sum() #checking missing values

import numpy as np
from sklearn.impute import SimpleImputer
numeric_cols = [
    'Monthly_Inhand_Salary',
    'Num_of_Delayed_Payment',
    'Changed_Credit_Limit',
    'Num_Credit_Inquiries',
    'Amount_invested_monthly',
    'Monthly_Balance'
]
num_imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
df[numeric_cols] = num_imputer.fit_transform(df[numeric_cols])
categorical_cols = [
    'Name',
    'Type_of_Loan',
    'Credit_History_Age'
]
cat_imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])
print(df.isna().sum())
#This code fills missing values:
#Numeric columns → replaced with the mean.
#Categorical columns → replaced with the most frequent value.
#Finally, it prints the updated missing value count.

# Identify numeric and categorical features
numeric_features = df.select_dtypes(include=['number']).columns.tolist()
categorical_features = df.select_dtypes(exclude=['number']).columns.tolist()

print("Numeric Features:")
print(numeric_features, "\n")

print("Categorical Features:")
print(categorical_features, "\n")

# Display distinct values for each categorical feature
for col in categorical_features:
    print(f"Column: {col}")
    print(df[col].unique())   # distinct values
    print("-" * 50)

