# -*- coding: utf-8 -*-
"""Day_2_Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f1FeYppXFFI4vtCeNCZuXvVHnzIbL-bn
"""

# import matplotlib.pyplot as plt
# plt.plot(x,y)

# plt.plot(ypoints,'*')
#* : star
#o : round
#s : square
#h : hexagonal
#p : pentagon
#d : diamond

#plt.plot(x,y,'*:r')
# *  marker
# :  line(solid line,dotted line)
# r  red

# : dotted line
# - solid line
# -- dashed line
# -. dashed/dotted line

#Line and Marker
#plt.plot(x,y,marker='o',ms=10,mec='r',mfc='g')
#ms : marker size
#mec : marker edge colour
#mfc : marker face colour

#line
#plt.plot(x,linestyle='dotted',color='r',linewidth=5)

#xlabel()
#ylabel()
#titile()

import matplotlib.pyplot as plt
x=[1,2,3,4]
y=[8,9,10,11]
plt.plot(x,y)

import numpy as np
x=np.array([1,2,6,8])
y=np.array([3,8,1,10])
plt.plot(x,y)

a=np.array([3,8,1,10,5,8,2])
plt.plot(a)

ypoints=np.array([3,9,5,2,7,6])
plt.plot(ypoints,'*')


#* : star
#o : round
#s : square
#h : hexagonal
#p : pentagon
#d : diamond

#Line and Marker

x=np.array([2,3,5,7])
y=np.array([8,6,9,2])
plt.plot(x,y,marker='o')

x=np.array([2,3,5,7])
y=np.array([8,6,9,2])
plt.plot(x,y,'*--r')
# *  marker
# :  line(solid line,dotted line)
# r  red

# : dotted line
# - solid line
# -- dashed line
# -. dashed/dotted line

x=np.array([2,3,5,7])
y=np.array([8,6,9,2])
plt.plot(x,y,'o-b')

x=np.array([2,3,5,7])
y=np.array([8,6,9,2])
plt.plot(x,y,'*--g')

x=np.array([2,3,5,7])
y=np.array([8,6,9,2])
plt.plot(x,y,'*-.y')

x=np.array([2,3,5,7])
plt.plot(x,marker='o',ms=10,mec='r',mfc='g')

#ms : marker size
#mec : marker edge colour
#mfc : marker face colour

#line

plt.plot(x,linestyle='dotted',color='r',linewidth=5)

x=np.array([2,3,5,7])
y=np.array([8,6,9,2])
w=[3,6,7,2,1]
z=[2,4,5,1,3]

plt.plot(x,y,marker='o')
plt.plot(w,z,marker='s')

#
height=[170,150,155,162]
weight=[70,50,45,68]
plt.plot(height,weight,'o-g')
plt.xlabel('Height in cm',color='m',size=10)
plt.ylabel('Weight in kg',color='m')
plt.title('Height-Weight Graph',color='r',size=20)

velocity=[45,48,55,50,52]
displacement=[150,200,200,175,200]
plt.plot(velocity,displacement,'o-g')
plt.xlabel('Velocity in kmph',color='r')
plt.ylabel('displacement in meter',color='r')
plt.title('Velocity-Displacement Graph',color='m',size=25)

"""# **Scatter Plot**"""

#Scatter plot

x1=[3,5,6,7,8]
y1=[6,3,2,4,7]
x2=[3,6,6,5,7]
y2=[7,3,4,6,2]
plt.scatter(x1,y1)
plt.scatter(x2,y2)

"""# **Grid**"""

x1=[3,5,6,7,8]
y1=[6,3,2,4,7]
plt.plot(x1,y1)
plt.xlabel('velocity')
plt.ylabel('displacement')
plt.title('Velocity - Displacement',color='r')
plt.grid(color='y',linestyle='dotted',linewidth=3) #axis='x' or 'y'

"""# **Subplot**"""

#Subplot : in one graph
#plt.subplot(val1,val2,val3)
#val1=row  val2=column  val3=order

x1=[1,2,3,4]
y1=[3,7,1,9]
plt.subplot(1,2,1)  #(val2,val2,val3)
plt.plot(x1,y1)
plt.xlabel('Velocity')
plt.ylabel('Displacement')
plt.title('Velocity - Displacement Graph')

x2=[3,5,6,1]
y2=[1,7,2,8]
plt.subplot(1,2,2)  #(val2,val2,val3)
plt.plot(x2,y2)
plt.xlabel('Height')
plt.ylabel('Weight')
plt.title('Height - Weight Graph')

plt.suptitle('Title Graph')

"""# **Bar Chart**"""

x1=[3,5,6,7,8]
y1=[6,3,2,4,7]
plt.bar(x1,y1)

x=['Aus','Eng','Ind','Pak','Nz','Wi','Ban']
y=[6,4,3,2,4,5,1]
plt.bar(x,y,color='g')  #vertical

# plt.barh  : horizontal

"""# **Histogram**"""

#Histogram()  most repeated values

x=[1,1,2,2,2,3,3,3,4,4,4,4,4,4]   #1:2, 2:3, 3:3, 4:6
plt.hist(x)

"""# **Pie Chart**"""

#pie chart

y=[10,20,30,40]
mylabel=['apple','orange','mango','grape']
mycolor=['black','red','hotpink','green']
plt.pie(y,labels=mylabel,shadow=True,colors=mycolor,autopct='%1.1f%%')
plt.legend(loc='lower right') #small box in side

