# -*- coding: utf-8 -*-
"""Day_2_Seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1faUoEoArz_uV__7kWo9BdQ5HYw05TEX_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=sns.load_dataset('tips')  #dummy dataset is loaded here
df

df.shape

df.isna().sum()

df.dtypes

#corelation : how to relate one column to another column

df.select_dtypes(include=np.number).corr()

#Heat map : graphical representaion of correlation
sns.heatmap(df.select_dtypes(include=np.number).corr())

#joint plot : used for numerical columns (like scatter plot + histogram), we can pass regression line,hexagonal
sns.jointplot(x='tip',y='total_bill',data=df,kind='reg')

sns.jointplot(x='tip',y='size',data=df,kind='hex')

#pair plot : combine plot for numerical values
sns.pairplot(df)

df.dtypes

df['sex'].value_counts()

df['smoker'].value_counts()

df['day'].value_counts()

df['time'].value_counts()

sns.pairplot(df,hue='sex')

sns.pairplot(df,hue='day') #hue means the side values small box

sns.pairplot(df,hue='smoker')

sns.pairplot(df,hue='time')

#count plot()

sns.countplot(x='sex',data=df,color='red',hue='day')

sns.countplot(x='smoker',data=df,color='green',hue='sex')

sns.countplot(x='day',data=df,color='yellow')

sns.countplot(x='time',data=df)

#barplot()

sns.barplot(x='total_bill',y='day',data=df)

sns.barplot(x='total_bill',y='time',data=df)

#Boxplot()
sns.boxplot(x='smoker',y='total_bill',data=df)  #outliers

#Percentile
#q1 : 25 percentile   q2 : 50 percentile    q3 : 75 percentile
#outliers

#3,5,7,1,1,8,4,6

#1,1,3,4,  5,6,7,8
#median= 4.5   q2:50 percentile

#q1: 1+3/2=2   25 percentile

#q3: 6+7/2=6.5  75 percentile

#IQR : Inter Quartile Range = q3-q1 = 6.5-2=4.5//

#Top : (1.5*IQR)+q3 = (1.5*4.5)+6.5=13.25
#Bot : q1-(1.5*IQR) = -4.75