# -*- coding: utf-8 -*-
"""pandas_import.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smAFVdJ7UFtU_MyHjPkc0xcJH6VLcpHT
"""

import pandas as pd
import numpy as np

#reading the files as the dataframe
df=pd.read_csv('/content/missing_data1.csv') #dataset->right click-> copy path->paste
df #print the data

df.head()

df.tail()

df.size

df.shape

df.dtypes

df.describe()

df.columns # to display column names

#missing values

df.isna()

df.isna().sum() #checking the missing values

#handling the missing values
#1. drop the rows with missing values

df1 = df.dropna()  #remove the rows and store it in the same variable or the different variable
df1.isna().sum()

#filling the missing values
#mean,median,mode
df2=df.fillna(df.mean(numeric_only=True))  #replacing with the mean the missing value
df2.isna().sum()

for col in df2.select_dtypes(include='object').columns:
  df2[col]=df2[col].fillna(df[col].mode()[0]) #object col we have the categories we can replace with most repated value(mode)

df2.isna().sum()

