# -*- coding: utf-8 -*-
"""Shaziya_Assessement1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yv3z5tmqHPj11q5F7byyT7AaFBxQyRlk
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/purchase_history (1).csv')
df

df.head()

df.tail()

df.isnull().sum()

df.info()

df.describe()

#imputation

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy= 'mean')
imputer.fit(df[['Age','SessionDuration']])
df[['Age','SessionDuration']] = imputer.transform(df[['Age','SessionDuration']])
df

df.isnull().sum()

from sklearn.impute import SimpleImputer
imputer1 = SimpleImputer(missing_values=np.nan,strategy= 'most_frequent')
df[['Gender']]=imputer1.fit_transform(df[['Gender']])
df

df.isnull().sum()

df.duplicated().sum() #no duplicates

sns.boxplot(df['TotalSpent'])

q1, q3 = np.percentile(df['TotalSpent'], [25, 75])
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)
print(lower_bound, upper_bound)
df = df[(df['TotalSpent'] >= lower_bound)  & (df['TotalSpent'] <= upper_bound)]
df

sns.boxplot(df['Age'])

q1, q3 = np.percentile(df['Age'], [25, 75])
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)
print(lower_bound, upper_bound)
df = df[(df['Age'] >= lower_bound)  & (df['Age'] <= upper_bound)]
df

sns.boxplot(df['SessionDuration'])

q1, q3 = np.percentile(df['SessionDuration'], [25, 75])
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)
print(lower_bound, upper_bound)
df = df[(df['SessionDuration'] >= lower_bound)  & (df['SessionDuration'] <= upper_bound)]
df

sns.boxplot(df['PagesVisited'])

q1, q3 = np.percentile(df['PagesVisited'], [25, 75])
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)
print(lower_bound, upper_bound)
df = df[(df['PagesVisited'] >= lower_bound)  & (df['PagesVisited'] <= upper_bound)]
df

sns.boxplot(df['Purchased'])# no outliers

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['Location']=le.fit_transform(df['Location'])
df['DeviceType']=le.fit_transform(df['DeviceType'])
df['ReferralSource']=le.fit_transform(df['ReferralSource'])
df['CustomerType']=le.fit_transform(df['CustomerType'])
df

from sklearn.preprocessing import StandardScaler
ssc = StandardScaler()
df[['Age','TotalSpent','SessionDuration','PagesVisited	']] = ssc.fit_transform(df[['Age','TotalSpent','SessionDuration','PagesVisited']])
df

#Linear Regression
#TRAIN TEST SPLIT
df2=df.copy()
from sklearn.model_selection import train_test_split
X=df.drop(['CustomerID','TotalSpent'],axis=1)
y=df['TotalSpent']
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=42)

print(df.shape)
print(X.shape)
print(y.shape)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

from sklearn.linear_model import LinearRegression
model= LinearRegression()
model.fit(X_train,y_train)

X_test

y_pred=model.predict(X_test)
y_pred

y_test

# Evaluating Metric
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
print(f'Mean Absolute Error: {mae}')

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

from sklearn.metrics import root_mean_squared_error
rmse =root_mean_squared_error(y_test, y_pred)
print(f'Root Mean Squared Error: {rmse}')

from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f'R-squared: {r2}')

#Classification
from sklearn.model_selection import train_test_split
X = df2.drop(['CustomerID','Purchased'], axis=1)
y = df2['Purchased']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state = 42)

print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)
print("Shape of y_train: ", y_train.shape)
print("Shape of y_test: ", y_test.shape)

# Model Selection Training -
# 1.Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)

y_test

y_pred = lr.predict(X_test)
y_pred

#Classification Evaluating matic
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# 2. kNN ALgorithm:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) #parameter means consider 5 neighbour (Values can be any) #this parameter is called hyperparameter
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
y_pred

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# 3. Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

y_pred = dtc.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# 4. SVM
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(X_train, y_train)

y_pred = svc.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# 5  Model GNB
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train, y_train)

y_pred = nb.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# 6. Random Forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

""" Here the best Model in Classification is the **GNB**(**Gaussian Navie Baye's Model**) because it has given accuracy of 1.0"""